language: python
python:
    - "3.5"
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install -r requirements.txt
script:
    - py.test --doctest-modules --cov
after_success:
    - coveralls